// Create a function computerPlay that generates one of 3 possible random options: rock, paper, scissors.
// computerPlay should use prompt()
// Create a function playRound that receives two inputs, a value given by a person (playerSelection) and a value generated by computerPlay (computerSelection). Then you have to compare and print the winner result like this: "You Lose! Paper beats Rock"
// playerSelection should not be case sensitive
// Declare a game function that will loop for five rounds, calling the playRound function each round and storing the score in two counters: one for the user and one for the machine. When I finished the loop, it should print the winner of the 5 rounds and generate the replay option, which will reset the counters to 0.
