// Create a function computerPlay that generates one of 3 possible random options: rock, paper, scissors.
function computerPlay() {
  return Math.floor(Math.random() * 100) > 66
    ? "Rock"
    : Math.floor(Math.random() * 100) > 33
    ? "Paper"
    : "Scissors";
}

// Create a function playRound that receives two inputs, a value given by a person (playerSelection) and a value generated by computerPlay (computerSelection). Then you have to compare and print the winner result like this: "You Lose! Paper beats Rock"

function playRound(playerSelection, computerSelection) {
  return (playerSelection == "Rock" && computerSelection == "Scissors") ||
    (playerSelection == "Paper" && computerSelection == "Rock") ||
    (playerSelection == "Scissors" && computerSelection == "Paper")
    ? `You win! ${playerSelection} beats ${computerSelection}`
    : playerSelection == computerSelection
    ? `Tie! There are not winner in this round`
    : `You Lose! ${computerSelection} beats ${playerSelection}`;
}

// Declare a game function that will loop for five rounds, calling the playRound function each round and storing the score in two counters: one for the user and one for the machine. When I finished the loop, it should print the winner of the 5 rounds and generate the replay option, which will reset the counters to 0.
function game() {
  console.log("Game started");
  console.log("\n");
  let counUser = 0;
  let countComputer = 0;
  let playerSelection1;
  let winner;
  let fiveCount = 0;
  while (counUser == countComputer || fiveCount < 5) {
    fiveCount++;
    // playerSelection should not be case sensitive
    // playerSelection should use prompt()
    playerSelection1 = prompt("Write your election")
      .split("")
      .map((letter, i) =>
        i == 0 ? letter.toUpperCase() : letter.toLowerCase()
      )
      .join("");

    // Check that the user Enter a valid option
    while (
      playerSelection1 != "Scissors" &&
      playerSelection1 != "Paper" &&
      playerSelection1 != "Rock"
    ) {
      playerSelection1 = prompt(
        "Please write a valid option: Rock, Paper or Scissors."
      )
        .split("")
        .map((letter, i) =>
          i == 0 ? letter.toUpperCase() : letter.toLowerCase()
        )
        .join("");
    }

    winner = playRound(playerSelection1, computerPlay());
    console.log("Round: " + fiveCount + " " + winner);
    if (/You win!/.test(winner)) {
      counUser++;
    } else if (/You Lose!/.test(winner)) {
      countComputer++;
    }

    console.log(
      `You have ${counUser} wins and Computer have ${countComputer} wins`
    );
    console.log("\n");
  }

  const result =
    counUser > countComputer
      ? `You have won ${counUser} to ${countComputer}`
      : `You have lost ${counUser} to ${countComputer}`;
  console.log(result);
  return result;
}

alert(
  "Press F12 or CTRL (or Command) + SHIFT + I to access the console and view the game."
);
while (true) {
  let start = prompt("Enter 'start' to start new game").toLowerCase();
  while (start != "start") {
    start = prompt("Enter 'start' to start new game").toLowerCase();
  }
  game();
}
